function [mean_el, draan, di] = osc2meanLinear(osc_el, params)
% osc2meanLinear transforms osculating elements to the mean one using
% linear approximation. See "Analytical Mechanics of Space Systems" by
% Schaub, Junkins, 2nd Edition, Appendix F, p. 775
% input:
% osc_el = [a; major semiaxis
%           e; eccentricity
%           inc; inclination
%           raan; argument of ascending node
%           aop; argument of perigee
%           f] true anomaly
% params: j2_coef
%         earth_radius
%         
a = osc_el(1);
e = osc_el(2);
inc = osc_el(3);
raan = osc_el(4);
aop = osc_el(5);
f = osc_el(6);

E = 2*atan(sqrt((1 - e)/(1 + e))*tan(f/2));
M = E - e*sin(E);

g2 = -params.j2_coef/2*(params.earth_radius/a)^2;
eta = sqrt(1 - e^2);
g2_dash = g2/eta^4;
a_r_ratio = (1 + e*cos(f))/eta^2;
ci = cos(inc);
a_mean = a + g2*a*(...
                   (3*ci^2 - 1)*(a_r_ratio^3 - 1/eta^3)...
                   + 3*(1 - ci^2)*a_r_ratio^3*cos(2*aop + 2*f)...
                   );
de1 = g2_dash^2/8*e*eta^2*(1 - 11*ci^2 - 40*ci^4/(1 - 5*ci^2))*cos(2*aop);
de = de1 + eta^2/2*(...
            g2*(3*ci^2 - 1)/eta^6*(e*eta + e/(1 + eta) + 3*cos(f) + 3*e*cos(f)^2 + e^2*cos(f)^3) ...
          + g2*3*(1 - ci^2)/eta^6*(e + 3*cos(f) + 3*e*cos(f)^2 + e^2*cos(f)^3)*cos(2*f + 2*aop) ...
          - g2_dash*(1 - ci^2)*(3*cos(2*aop + f) + cos(2*aop + 3*f)) ...
           );
di = -e*de1/eta^2/tan(inc) + g2_dash/2*ci*sqrt(1 - ci^2)*(...
     3*cos(2*aop + 2*f) + 3*e*cos(2*aop + f) + e*cos(2*aop + 3*f)...
     );

draan = -g2_dash/8*e^2*ci*(11 + 80*ci^2/(1 - 5*ci^2) + 200*ci^4/(1 - 5*ci^2)^2)...
        -g2_dash/2*ci*(6*(f - M + e*sin(f)) - 3*sin(2*aop + 2*f)...
                      -3*e*sin(2*aop + f) - e*sin(2*aop + 3*f));
dsum_all = M + aop + raan ...
         + g2_dash/8*eta^3*(1 - 11*ci^2 - 40*ci^4/(1  - 5*ci^2))...
         - g2_dash/16*(2 + e^2 - 11*(2 + 3*e^2)*ci^2 - 40*(2 + 5*e^2)*ci^4/(1 - 5*ci^2)...
                       -400*e^2*ci^6/(1 - 5*ci^2)^2 ...
                       )...
         + g2_dash/4*(-6*(1 - 5*ci^2)*(f - M + e*sin(f))...
                      +(3 - 5*ci^2)*(3*sin(2*aop + 2*f) + 3*e*sin(2*f + aop)...
                      + e*sin(2*aop + 3*f)))...
         + draan;
edM = g2_dash/8*e*eta^3*(1 - 11*ci^2 - 40*ci^4/(1 - 5*ci^2))...
    - g2_dash/4*eta^3*(2*sin(f)*(3*ci^2 - 1)*((a_r_ratio*eta)^2 + a_r_ratio + 1)...
                     + 3*(1 - ci^2)*( (-(a_r_ratio*eta)^2 - a_r_ratio + 1)*sin(2*aop + f)...
                                     + ((a_r_ratio*eta)^2 + a_r_ratio + 1/3)*sin(2*aop + 3*f) )...
                      );
d1 = (e + de)*sin(M) + edM*cos(M);
d2 = (e + de)*cos(M) - edM*sin(M);
M_mean = atan2(d1,d2);
e_mean = sqrt(d1^2 + d2^2);
d3 = (sin(inc/2) + cos(inc/2)*di/2)*sin(raan) + sin(inc/2)*draan*cos(raan);
d4 = (sin(inc/2) + cos(inc/2)*di/2)*cos(raan) - sin(inc/2)*draan*sin(raan);
raan_mean = atan2(d3, d4);
inc_mean = 2*asin(sqrt(d3^2 + d4^2));
aop_mean = dsum_all - M_mean - raan_mean;
[~, f_mean] = utility_funcs.keplerEqSolve(M_mean, e_mean);
mean_el = [a_mean; e_mean; inc_mean; raan_mean; aop_mean; f_mean];
end